dubbo:
  application:
    name: dubbo-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.address}?username=${nacos.username}&password=${nacos.password}&namespace=${nacos.namespace}


nacos:
  username: nacos
  password: nacos
  address: 127.0.0.1:8848
  namespace: dev